In [1]:
import tensorflow as tf

In [3]:
tf.config.list_physical_devices('GPU')

[]

In [5]:
[device.name for device in tf.config.experimental.list_physical_devices()]

['/physical_device:CPU:0',
 '/physical_device:XLA_CPU:0',
 '/physical_device:XLA_GPU:0']

In [8]:
x=tf.constant(1)
y=tf.constant(2)
c=x+y
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [10]:
x1=tf.constant([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(x1)

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]], shape=(3, 3), dtype=float32)


In [11]:
type(x1)

tensorflow.python.framework.ops.EagerTensor

In [13]:
x=tf.matmul(x1,x1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 30.,  36.,  42.],
       [ 66.,  81.,  96.],
       [102., 126., 150.]], dtype=float32)>

In [14]:
x=tf.ones([2,2])
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [15]:
x=tf.zeros([2,2])
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [19]:
c=tf.sqrt(tf.constant(3.0**2)+tf.constant(4.0**2))
c

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

In [24]:
x=tf.constant(3)
x=tf.add(x,2)
x

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [25]:
A=tf.constant([[1,2],[3,4]])
B=tf.constant([[1,3],[5,6]])
A+B

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 8, 10]])>

In [26]:
con=tf.concat([A,B],axis=1)
con

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 1, 3],
       [3, 4, 5, 6]])>

In [27]:
dotp=tf.tensordot(a=A,b=B,axes=1)
dotp

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 15],
       [23, 33]])>

In [28]:
import time
def t_matmul(x):
    st = time.time()
    for loop in range(10):
        tf.matmul(x,x)
    res = time.time() - st
    print('10 loops: {:0.2}ms'.format(1000*res))

print('on CPU: ')

with tf.device('CPU:0'):
    x = tf.random.uniform([1000,1000])
    assert x.device.endswith('CPU:0')
    t_matmul(x)

on CPU: 
10 loops: 1.2e+02ms


In [32]:
import tensorflow as tf
if tf.test.is_gpu_available():
      print('On GPU')

with tf.device.endswith('XLA_GPU:0'):
    x = tf.random.uniform([1000,1000])
    assert x.device.endswith('GPU:0')
    t_matmul(x)

AttributeError: 'function' object has no attribute 'endswith'

In [40]:
from datetime import datetime
#from package import package

# set up logging
stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
logdir = 'logs/func/%s' % stamp

writer = tf.summary.create_file_writer(logdir)

a = tf.Variable(1.0)
b = tf.Variable(2.0)
@tf.function
def f(x,y):
    a.assign(y*b)  # a ==> 4
    b.assign_add(x*a) # b => 4 * 1+ 2 => 6
    return a+b

tf.summary.trace_on(graph=True,profiler=True)

with writer.as_default():
    tf.summary.trace_export(
    name = 'my_test_trace',step=0,profiler_outdir=logdir)

In [41]:
f(1.0,2.0)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>